version: "2"

services:
  base:
    build:
      context: ./base
    image: dccn-dicomdf-base
    networks:
      - nw-dicom-dataflow
  orthanc:
    build: ./orthanc
    image: dccn-dicomdf-orthanc
    networks:
      - nw-dicom-dataflow
    hostname: orthanc
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc/config:/var/lib/orthanc/etc:ro
      - vol-orthanc-log:/var/lib/orthanc/log
      - vol-orthanc-db:/var/lib/orthanc/db
      - vol-orthanc-idx:/var/lib/orthanc/idx
    environment:
      - STREAMER_URL=http://streamer:3001
  wlbroker:
    build: ./wlbroker
    image: dccn-dicomdf-wlbroker
    depends_on:
      - base
    networks:
      - nw-dicom-dataflow
    hostname: wlbroker
    ports:
      - 1234:1234
    volumes:
      - vol-wlbroker:/data/wlbroker
  cal2wl:
    build: ./cal2wl
    image: dccn-dicomdf-cal2wl
    depends_on:
      - base
    networks:
      - nw-dicom-dataflow
    hostname: cal2wl
    volumes:
      - ./cal2wl/config:/opt/config:ro
      - vol-wlbroker:/data/wlbroker

networks:
  nw-dicom-dataflow:
    external: true

volumes:
  vol-orthanc-db:
    external: true
  vol-orthanc-idx:
    external: true
  vol-orthanc-log:
    external: true
  vol-wlbroker:
    external: true
